# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04493ed296a640fbb34ab77b57763c305627ed1c6c4d0b9ea36eb602917bda42d739be9f5ba40c5ef8121ed696bcec88392fcdef00d6356eec10dcc798755110

test:
  secret_key_base: 40a950167adcc66b533c7f523048a48bb34badf75e7a3c65cb10265d1867f8d86438a52d3ea83493f65129790cbff721475ea27cb62bb744f6e438ccd1d72d3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
